[package]
name = "yarn-hoard-api"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "api", "entity", "migration"]

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
api = { path = "api" }
axum = "0.8.1"
entity = { path = "entity" }
migration = { path = "migration" }
tokio = { version = "1.44.1" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
