[package]
name = "yarn-hoard"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "1"
members = [ "entity", "migration"]

[[bin]]
name = "frontend"
path = "src/bin/frontend.rs"

[[bin]]
name = "backend"
path = "src/bin/backend.rs"

[lib]
name = "yarn_hoard"
path = "src/lib/lib.rs"

[dependencies]
# Internal
entity = { path = "./entity" }
migration = { path = "./migration" }

# External
anyhow = "1.0.97"
axum = "0.8.1"
console_error_panic_hook = "0.1.7"
hex = "0.4.3"
openssl = { version = "0.10.71", features = [ "vendored" ] }
reqwest = { version = "0.12.15", features = ["json"] }
sea-orm = { version = "1.1.7", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
secrecy = { version = "0.10.3", features = ["serde"] }
serde = "1.0.219"
serde_json = "1.0.140"
sycamore = { version = "0.9.1", features = ["suspense"] }
sycamore-router = "0.9.1"
thiserror = "2.0.12"
tokio = { version = "1.44.1" }
tower-http = { version = "0.6.2", features = ["trace", "cors"] }
tracing-wasm = "0.2.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
testcontainers-modules = { version = "0.11.6", features = ["postgres"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(sycamore_force_ssr)"] }
