[package]
name = "yarn-hoard-api"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "entity", "migration"]

[[bin]]
name = "yarn-hoard-api"
path = "src/bin/main.rs"

[lib]
name = "api"
path = "src/lib/lib.rs"

[dependencies]
# Internal 
entity = { path = "entity" }
migration = { path = "migration" }

# External
anyhow = "1.0.97"
axum = "0.8.1"
axum-extra = { version = "0.10.0", features = ["erased-json"] }
hex = "0.4.3"
openssl = { version = "0.10.71", features = [ "vendored" ] }
paste = "1.0.15"
sea-orm = { version = "1.1.7", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
serde = "1.0.219"
secrecy = { version = "0.10.3", features = ["serde"] }

[dev-dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
testcontainers-modules = { version = "0.11.6", features = ["postgres"] }
