services:
  # site:
  #   build:
  #     context: .
  #     target: base 
  #   command: trunk serve --config=site/Trunk.toml --address=0.0.0.0
  #   ports:
  #     - 8080:8080
  #   environment:
  #     API_URL: "localhost:3000"
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: .
  #         target: /app

  api-server:
    depends_on:
      db:
        condition: service_started 
        restart: true
    build: 
      context: .
      target: base
    command: cargo run --bin backend
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://yarn_hoard:password@db:5432/yarn_hoard
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app

  db:
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: yarn_hoard
      POSTGRES_PASSWORD: password
    # volumes:
    # - ./data:/var/lib/postgresql/data

