services:
  api:
    depends_on:
      db:
        condition: service_started 
        restart: true
    build: 
      context: .
      target: dev
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://yarn_hoard:password@db:5432/yarn_hoard
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore: 
          - target
  db:
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: yarn_hoard
      POSTGRES_PASSWORD: password
    volumes:
    - ./data:/var/lib/postgresql/data

