[package]
name = "api-client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
secrecy = "0.10.3"
serde_json = "1.0.140"
thiserror = "2.0.12"
tracing = "0.1.41"
