[package]
name = "site"
version = "0.1.0"
edition = "2024"

[dependencies]
sycamore = "0.9.1"
sycamore-router = "0.9.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(sycamore_force_ssr)"] }
