//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub hashed_password: String,
    pub salt: String,
    pub is_activated: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::confirmations::Entity")]
    Confirmations,
}

impl Related<super::confirmations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Confirmations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
